Repository Ahmed-cmd-web/DATABASED, pull requests merged in 2023-12, with the labels that each got.

#117 Add FN_StudentCheckSMEligiability
  index.sql
Labels: enhancement

#123 Add Procedures_AdminDeleteCourse
  debug.sql
  index.sql
Labels: enhancement

#148 add Procedures_StudentSendingCourseRequest
  index.sql
Labels: enhancement

#141 Add Procedures_StudentaddMobile
  index.sql
Labels: enhancement

#137 Finished Fix issue/#72 and #73
  index.sql
Labels: enhancement

#139 Add Procedures_AdvisorViewPendingRequests
  debug.sql
  index.sql
Labels: enhancement

#143 Add FN_StudentUpcoming_installment
  debug.sql
  index.sql
Labels: enhancement

#138 Add Procedures_ViewOptionalCourse
  debug.sql
  index.sql
Labels: bug, help wanted, invalid, wontfix

#207 Add Advisor Register to the website
  webASP/AdvisorRegisterForm.aspx
  webASP/AdvisorRegisterForm.aspx.cs
  webASP/AdvisorRegisterForm.aspx.designer.cs
  webASP/webASP.csproj
Labels: enhancement, Advisor Component

#209 Add Main Form for advisor viewing his advising students
  webASP/AdvisorAddCourseForm.aspx
  webASP/AdvisorAddCourseForm.aspx.cs
  webASP/AdvisorAddCourseForm.aspx.designer.cs
  webASP/AdvisorAddGPForm.aspx
  webASP/AdvisorAddGPForm.aspx.cs
  webASP/AdvisorAddGPForm.aspx.designer.cs
  webASP/AdvisorDeleteCourseForm.aspx
  webASP/AdvisorDeleteCourseForm.aspx.cs
  webASP/AdvisorDeleteCourseForm.aspx.designer.cs
  webASP/AdvisorMainForm.aspx
  webASP/AdvisorMainForm.aspx.cs
  webASP/AdvisorMainForm.aspx.designer.cs
  webASP/AdvisorRegisterForm.aspx.cs
  webASP/AdvisorSignupForm.aspx.cs
  webASP/AdvisorUpdateExpectedGPDateForm.aspx
  webASP/AdvisorUpdateExpectedGPDateForm.aspx.cs
  webASP/AdvisorUpdateExpectedGPDateForm.aspx.designer.cs
  webASP/images/addCourseBtnIcon.png
  webASP/images/addGpBtnIcon.png
  webASP/images/deleteCourseBtnIcon.png
  webASP/images/updateDateGPBtnIcon.png
  webASP/webASP.csproj
Labels: enhancement, question
